
export const latitude = 53.501672;
export const longitude = -2.195222;

export const events = [
    {
        id: 1,
        type: 'Pubs & bars',
        title: '241 Cocktails',
        address: 'Gem Bar, 321 Milton Street',
        coordinate: {
            latitude: latitude + 0.010,
            longitude: longitude,
        },
        details: '241 cocktails 7-9pm',
        image: '',
        date: '31 Jul 2017',
        time: '',
        sponsored: false,
        userId: '',
        recurring: ''
    },
    {
        id: 2,
        type: 'Theatre',
        title: '10% off GoT tickets!',
        address: 'Jacob\'s Theatre, 15 Oldham Street',
        coordinate: {
            latitude: latitude + 0.004,
            longitude: longitude + 0.004,
        },
        details: '10% off tickets for \'Game of Thrones: the musical\'',
        image: '',
        date: '30 Jul 2017',
        time: '',
        sponsored: false,
        userId: '',
        recurring: ''
    },
    {
        id: 3,
        type: 'Restaurants',
        title: 'Free starter',
        address: 'Tony\'s Trattoria, 43 Newton Road',
        coordinate: {
            latitude: latitude + 0.014,
            longitude: longitude + 0.020,
        },
        details: 'Free starter with every meal',
        image: '',
        date: '28 Jul 2017',
        time: '',
        sponsored: false,
        userId: '',
        recurring: ''
    },
    {
        id: 4,
        type: 'Pubs & bars',
        title: '241 Cocktails',
        address: 'Gem Bar, 321 Milton Street',
        coordinate: {
            latitude: latitude + 0.024,
            longitude: longitude + 0.030,
        },
        details: '241 cocktails 7-9pm',
        image: '',
        date: '31 Jul 2017',
        time: '',
        sponsored: false,
        userId: '',
        recurring: ''
    },
    {
        id: 5,
        type: 'Theatre',
        title: '10% off GoT tickets!',
        address: 'Jacob\'s Theatre, 15 Oldham Street',
        coordinate: {
            latitude: latitude + 0.034,
            longitude: longitude + 0.004,
        },
        details: '10% off tickets for \'Game of Thrones: the musical\'',
        image: '',
        date: '30 Jul 2017',
        time: '',
        sponsored: false,
        userId: '',
        recurring: ''
    },
    {
        id: 6,
        type: 'Restaurants',
        title: 'Free starter',
        address: 'Tony\'s Trattoria, 43 Newton Road',
        coordinate: {
            latitude: latitude + 0.034,
            longitude: longitude + 0.010,
        },
        details: 'Free starter with every meal',
        image: '',
        date: '28 Jul 2017',
        time: '',
        sponsored: false,
        userId: '',
        recurring: ''
    },
    {
        id: 7,
        type: 'Pubs & bars',
        title: '241 Cocktails',
        address: 'Gem Bar, 321 Milton Street',
        coordinate: {
            latitude: latitude + 0.010,
            longitude: longitude + 0.009,
        },
        details: '241 cocktails 7-9pm',
        image: '',
        date: '31 Jul 2017',
        time: '',
        sponsored: false,
        userId: '',
        recurring: ''
    },
    {
        id: 8,
        type: 'Theatre',
        title: '10% off GoT tickets!',
        address: 'Jacob\'s Theatre, 15 Oldham Street',
        coordinate: {
            latitude: latitude + 0.004,
            longitude: longitude + 0.022,
        },
        details: '10% off tickets for \'Game of Thrones: the musical\'',
        image: '',
        date: '30 Jul 2017',
        time: '',
        sponsored: false,
        userId: '',
        recurring: ''
    },
    {
        id: 9,
        type: 'Restaurants',
        title: 'Free starter',
        address: 'Tony\'s Trattoria, 43 Newton Road',
        coordinate: {
            latitude: latitude + 0.005,
            longitude: longitude + 0.028,
        },
        details: 'Free starter with every meal',
        image: '',
        date: '28 Jul 2017',
        time: '',
        sponsored: false,
        userId: '',
        recurring: ''
    },
    {
        id: 10,
        type: 'Pubs & bars',
        title: '241 Cocktails',
        address: 'Gem Bar, 321 Milton Street',
        coordinate: {
            latitude: latitude + 0.031,
            longitude: longitude + 0.002,
        },
        details: '241 cocktails 7-9pm',
        image: '',
        date: '31 Jul 2017',
        time: '',
        sponsored: false,
        userId: '',
        recurring: ''
    },
    {
        id: 11,
        type: 'Theatre',
        title: '10% off GoT tickets!',
        address: 'Jacob\'s Theatre, 15 Oldham Street',
        coordinate: {
            latitude: latitude + 0.039,
            longitude: longitude + 0.012,
        },
        details: '10% off tickets for \'Game of Thrones: the musical\'',
        image: '',
        date: '30 Jul 2017',
        time: '',
        sponsored: false,
        userId: '',
        recurring: ''
    },
    {
        id: 12,
        type: 'Restaurants',
        title: 'Free starter',
        address: 'Tony\'s Trattoria, 43 Newton Road',
        coordinate: {
            latitude: latitude + 0.019,
            longitude: longitude + 0.018,
        },
        details: 'Free starter with every meal',
        image: '',
        date: '28 Jul 2017',
        time: '',
        sponsored: false,
        userId: '',
        recurring: ''
    },
    {
        id: 13,
        type: 'Pubs & bars',
        title: '241 Cocktails',
        address: 'Gem Bar, 321 Milton Street',
        coordinate: {
            latitude: latitude + 0.015,
            longitude: longitude,
        },
        details: '241 cocktails 7-9pm',
        image: '',
        date: '31 Jul 2017',
        time: '',
        sponsored: false,
        userId: '',
        recurring: ''
    },
    {
        id: 14,
        type: 'Theatre',
        title: '10% off GoT tickets!',
        address: 'Jacob\'s Theatre, 15 Oldham Street',
        coordinate: {
            latitude: latitude + 0.016,
            longitude: longitude + 0.009,
        },
        details: '10% off tickets for \'Game of Thrones: the musical\'',
        image: '',
        date: '30 Jul 2017',
        time: '',
        sponsored: false,
        userId: '',
        recurring: ''
    },
    {
        id: 15,
        type: 'Restaurants',
        title: 'Free starter',
        address: 'Tony\'s Trattoria, 43 Newton Road',
        coordinate: {
            latitude: latitude + 0.026,
            longitude: longitude + 0.022,
        },
        details: 'Free starter with every meal',
        image: '',
        date: '28 Jul 2017',
        time: '',
        sponsored: false,
        userId: '',
        recurring: ''
    },
    {
        id: 16,
        type: 'Pubs & bars',
        title: '241 Cocktails',
        address: 'Gem Bar, 321 Milton Street',
        coordinate: {
            latitude: latitude + 0.010,
            longitude: longitude + 0.031,
        },
        details: '241 cocktails 7-9pm',
        image: '',
        date: '31 Jul 2017',
        time: '',
        sponsored: false,
        userId: '',
        recurring: ''
    },
    {
        id: 17,
        type: 'Theatre',
        title: '10% off GoT tickets!',
        address: 'Jacob\'s Theatre, 15 Oldham Street',
        coordinate: {
            latitude: latitude + 0.023,
            longitude: longitude + 0.003,
        },
        details: '10% off tickets for \'Game of Thrones: the musical\'',
        image: '',
        date: '30 Jul 2017',
        time: '',
        sponsored: false,
        userId: '',
        recurring: ''
    },
    {
        id: 18,
        type: 'Restaurants',
        title: 'Free starter',
        address: 'Tony\'s Trattoria, 43 Newton Road',
        coordinate: {
            latitude: latitude + 0.033,
            longitude: longitude + 0.011,
        },
        details: 'Free starter with every meal',
        image: '',
        date: '28 Jul 2017',
        time: '',
        sponsored: false,
        userId: '',
        recurring: ''
    },
    {
        id: 19,
        type: 'Pubs & bars',
        title: '241 Cocktails',
        address: 'Gem Bar, 321 Milton Street',
        coordinate: {
            latitude: latitude + 0.029,
            longitude: longitude + 0.036,
        },
        details: '241 cocktails 7-9pm',
        image: '',
        date: '31 Jul 2017',
        time: '',
        sponsored: false,
        userId: '',
        recurring: ''
    },
    {
        id: 20,
        type: 'Theatre',
        title: '10% off GoT tickets!',
        address: 'Jacob\'s Theatre, 15 Oldham Street',
        coordinate: {
            latitude: latitude + 0.001,
            longitude: longitude + 0.019,
        },
        details: '10% off tickets for \'Game of Thrones: the musical\'',
        image: '',
        date: '30 Jul 2017',
        time: '',
        sponsored: false,
        userId: '',
        recurring: ''
    },
    {
        id: 21,
        type: 'Restaurants',
        title: 'Free starter',
        address: 'Tony\'s Trattoria, 43 Newton Road',
        coordinate: {
            latitude: latitude + 0.006,
            longitude: longitude + 0.017,
        },
        details: 'Free starter with every meal',
        image: '',
        date: '28 Jul 2017',
        time: '',
        sponsored: false,
        userId: '',
        recurring: ''
    }
];
